"""Add advanced sync models: DeviceRole, SyncState, MasterElectionLog

Revision ID: 43822a08f37b
Revises: 8a1213f04992
Create Date: 2025-07-26 12:41:58.722077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43822a08f37b'
down_revision = '8a1213f04992'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('device_roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_roles_device_id'), ['device_id'], unique=True)

    op.create_table('master_election_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('previous_master_id', sa.String(length=255), nullable=True),
    sa.Column('new_master_id', sa.String(length=255), nullable=False),
    sa.Column('election_reason', sa.String(length=50), nullable=False),
    sa.Column('election_timestamp', sa.DateTime(), nullable=False),
    sa.Column('devices_participating', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sync_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=255), nullable=False),
    sa.Column('last_sync_timestamp', sa.DateTime(), nullable=True),
    sa.Column('sync_status', sa.String(length=50), nullable=False),
    sa.Column('pending_changes_count', sa.Integer(), nullable=False),
    sa.Column('last_error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sync_state', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_state_device_id'), ['device_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sync_state', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_state_device_id'))

    op.drop_table('sync_state')
    op.drop_table('master_election_log')
    with op.batch_alter_table('device_roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_roles_device_id'))

    op.drop_table('device_roles')
    # ### end Alembic commands ###
