"""Initial migration with sync_events table

Revision ID: 8a1213f04992
Revises: 
Create Date: 2025-07-25 13:41:19.369814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a1213f04992'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sync_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_events_device_id'), ['device_id'], unique=False)
        batch_op.create_index('ix_sync_events_device_status', ['device_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_events_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_events_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_events_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sync_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_sync_events_timestamp'))
        batch_op.drop_index(batch_op.f('ix_sync_events_status'))
        batch_op.drop_index('ix_sync_events_device_status')
        batch_op.drop_index(batch_op.f('ix_sync_events_device_id'))

    op.drop_table('sync_events')
    # ### end Alembic commands ###
